<?php
function jack_block_info() {
$block['jack-block'] = array(
'info' => 'Bonjour !',
);
return $block;
}
function jack_block_view($delta = ''){
$block['subject'] = 'Mon contenu';
$block['content'] = jack_block_contents($delta); 
return $block;
}
function jack_block_contents($delta){
return 'ceci est mon premier bloc';
}
function jack_menu() {
	$items['jack'] = array(
	'title' => 'Mon Formulaire',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('jack_nameform'),
	'access callback' => TRUE,
	'type' => MENU_NORMAL_ITEM);
	return $items;
}
function jack_nameform() {
	$form['user name'] = array(
		'#title' => 'your name',
		'#type' => 'textfield',
		'#description' => 'please enter your name',
		);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'envoyer');  		 	
	return $form;
}

function jack_nameform_submit($form, &$form_state) {
	$name = $form_state['value']['user name'];
	drupal_set_message(array('%name' => $name));
}
